Web client
spine-examples/server-quickstart pull request #12
Opened 2019-04-30 11:01 UTC by dmdashenkov

2019-05-06 15:40 UTC, dmdashenkov commented
@armiol, PTAL.

2019-05-07 11:52 UTC, armiol requested changes
@dmdashenkov please see my comments.

2019-05-07 11:52 UTC, armiol commented on web/README.md
> +    - build a single javascript artifact via `webpack`.
`JavaScript`.

2019-05-07 11:52 UTC, armiol commented on web/server/src/main/java/io/spine/quickstart/web/package-info.java
> +package io.spine.quickstart.web;
Please describe the package.

2019-05-07 11:52 UTC, armiol commented on web/server/src/main/java/io/spine/quickstart/web/TasksCommandServlet.java
> +public final class TasksCommandServlet extends CommandServlet {
Please have Javadocs for this and other servlets.

2019-05-07 11:52 UTC, armiol commented on web/client/src/main/index.js
> +class TaskController {
Please document this class and two functions below.

2019-05-07 17:17 UTC, dmdashenkov commented
@armiol, PTAL again.

2019-05-10 11:32 UTC, dmdashenkov commented
@armiol, PTAL again.

2019-05-10 12:43 UTC, armiol approved these changes

2019-05-10 12:43 UTC, armiol commented on web/client/build.gradle
> +protobuf {
Let's create a task to include the configuration like this one and the one above into the Bootstrap plugin.

2019-05-10 12:49 UTC, merged