Add more details to README
spine-examples/server-quickstart pull request #8
Opened 2019-03-27 13:39 UTC by dmdashenkov

This PR widens the `README.md` with more details on the project structure and links to other resources.

The objective of the resulting document is to get the newcomer developers a kick-start on the Spine development.

2019-03-27 14:06 UTC, dmdashenkov commented
@meizabel, PTAL.
@alexander-yevsyukov, @armiol, PTAL as well.

2019-03-27 18:10 UTC, alexander-yevsyukov commented on README.md
> + * Register the newly created repositories in the bounded context.
Please capitalize Bounded Context.

2019-03-27 18:17 UTC, alexander-yevsyukov commented on README.md
>  Defines the [ubiquitous language](https://martinfowler.com/bliki/UbiquitousLanguage.html)
Please capitalize Ubiquitous Language.

2019-03-27 18:18 UTC, alexander-yevsyukov commented on README.md
> + * `TaskCreated` in `events.proto` is an event of the `Task` aggregate;
`TaskAggregate` must be a class name. Otherwise it is confusing.

2019-03-27 18:20 UTC, alexander-yevsyukov commented on README.md
> +### Suggested `model` Changes
There must be a simple change to a model. Without surrounding waters. Add a field to a command, add one more command. Make it really simple.

2019-03-27 18:22 UTC, alexander-yevsyukov commented on README.md
> + * Design and implement Aggregates, Projections and Process Managers on top of the previously
Remove water.

2019-03-27 18:25 UTC, alexander-yevsyukov requested changes
Please simplify the text as we discussed vocally recently. Remove all abstract things. Do not make it a tutorial. For changing current code suggest something simple, like adding a field to a command.

2019-03-28 14:12 UTC, alexander-yevsyukov requested changes
We're close. Please see my comments.

2019-03-28 14:12 UTC, alexander-yevsyukov commented on README.md
> +    google.protobuf.Timestamp due_date = 2 [(when).in = FUTURE];
Please use `LocalDate` instead.

2019-03-28 14:12 UTC, alexander-yevsyukov commented on README.md
> +// -- commands.proto --
Have something like: Please add the following message to `commands.proto` file.

2019-03-28 14:12 UTC, alexander-yevsyukov commented on README.md
> +// -- events.proto --
Similarly, please add instruction for updating `events.proto` file.

2019-03-28 14:12 UTC, alexander-yevsyukov commented on README.md
> +Make sure to run a Gradle build after the changing the Protobuf definitions.
Please add command line.

2019-03-28 14:12 UTC, alexander-yevsyukov commented on README.md
> + * In `ClientApp`, append the `main()` method. Post another command:
Did you mean ”extend”? The word ”append” sounds as we're adding yet another method to the bottom of the class source code.

2019-03-28 15:20 UTC, dmdashenkov commented
@alexander-yevsyukov, PTAL again.

2019-03-28 15:50 UTC, alexander-yevsyukov reviewed
Please see my comments.

2019-03-28 15:50 UTC, alexander-yevsyukov commented on client/src/main/java/io/spine/quickstart/client/ClientApp.java
> +    public static void main(String[] args) throws InterruptedException, ParseException {
Do we still need `ParseException`?

2019-03-28 15:50 UTC, alexander-yevsyukov commented on README.md
> +    spine.time.LocalDate due_date = 2;
Isn't it `required`?

2019-03-28 15:50 UTC, alexander-yevsyukov commented on README.md
> +    spine.time.LocalDate due_date = 2;
Isn't this `required`?

2019-03-28 15:50 UTC, alexander-yevsyukov commented on README.md
> +
Please remove extra line.

2019-03-28 17:15 UTC, dmdashenkov commented
@alexander-yevsyukov, PTAL again.

2019-03-28 17:43 UTC, alexander-yevsyukov requested changes
Please see my comments.

2019-03-28 17:43 UTC, alexander-yevsyukov commented on README.md
> +QueryResponse updatedStateResponse = queryService.read(readAllTasks);
Please read only the task we're dealing with.

2019-03-28 17:43 UTC, alexander-yevsyukov commented on client/src/main/java/io/spine/quickstart/client/ClientApp.java
> +        CreateTask createTask = newCreateTaskCommand(taskId, "Wash my car");
Please think of something else for the task.

2019-03-28 17:52 UTC, alexander-yevsyukov approved these changes
LGTM

2019-03-28 18:01 UTC, merged